aws-samples/amazon-bedrock-agents-healthcare-lifesciences

- ActionGroups/querydatabaselambda/querydatabaselambda.py
- Infra_cfn.yaml
- streamlitapp/app.py
- streamlitapp/util/bedrock.py
Added new refine query prompt in lambda function 
Changed Survival_Status column to BOOLEAN
> Infrayamlupdates

- README.md
- agent_build.yaml
- streamlitapp/app.py
UI additions - question list and renaming the actions
Add deployment instructions
Disable code interpreter 
> UI updates and readme instructions updated

- ActionGroups/scientific-plots-with-lifelines/app.py
1. Added fix for CoxPHFitter initialization
2. Implemented error handling
> Cox ph fittererrorfix

- ActionGroups/matplotbarchartlambda/matplotbarchartlambda.py
- agent_build.yaml
- lambdalayers/requirements.txt
I added matplotbarchart tool which can create a bar chart from the given inputs and saves it into s3 bucket,
> Matplotbarchart tool

- agent_build.yaml
> enabled user input in the agent

- Infra_cfn.yaml
- README.md
- agent_build.yaml
- streamlitapp/Infra_cfn.yaml
- streamlitapp/app.py
- streamlitapp/streamlit_build.yaml
- streamlitapp/util/bedrock.py
Updated infrastructure policies to be more secure
Added cloudfront distribution and enabled https 
Reduced Agent instruction to be under 4000 characters 
> Zeekgcodefixes

- README.md
This PR simply adds information about multi-agent deployment availability to the top of the main branch's README.
> Updated README.md to include multi-agent update

- README.md
Much easier to clone GitHub repository directory than to download and upload as a .zip file
> Updated README.md with most up-to-date instructions

- Infra_cfn.yaml
MultiAgentDevMode duplicate reference
> MultiAgentDevMode duplicate reference

- README.md
Need to put "https://" at beginning for some browsers
> Fix README.md for Streamlit App

- agents_catalog/0-Notebook-environment/requirements.txt
Adds datasets to requirements.txt
> Fix requirements.txt

- Infra_cfn.yaml
- agent_build.yaml
- agents/Biomarker-database-analyst.yaml
- agents/Clinical-evidence-researcher.yaml
- agents/Medical-imaging-expert.yaml
- agents/Statistician.yaml
Multiagentdevmode = true now builds all lambda functions 
> Multiagentfixes

- agent_build.yaml
- agents/Medical-imaging-expert.yaml
add permission due to lambda permission error
> permission error fix

- agents_catalog/5-Biological-pathways-analyst/text2cypher_infra.yaml
Using 3 subnets instead of 6 and not creating a Neptune Notebook anymore
> Updated text2cypher_infra.yaml to fix VPC issue

- agents_catalog/Create-your-own-agent/bring_your_own_data/text2cypher_neptune/README.MD
> Update README.MD for Bring your own data

- agents_catalog/7-Pathology-Agent/LambdaAgent/lambda_function.py
- agents_catalog/7-Pathology-Agent/LambdaWSI_Viewer/lambda_function.py
- agents_catalog/7-Pathology-Agent/create_agent.ipynb
> Small Pathology Fix

- multi_agent_collaboration/competitive_intelligence/README.md
> Fix CI supervisor README

- agents_catalog/18-Wiley-online-library-agent/.gitignore
- agents_catalog/18-Wiley-online-library-agent/README.md
- agents_catalog/18-Wiley-online-library-agent/action-groups/wiley-search/index.py
- agents_catalog/18-Wiley-online-library-agent/bedrock_agent_wrapper.py
- agents_catalog/18-Wiley-online-library-agent/demo_tools/__init__.py
- agents_catalog/18-Wiley-online-library-agent/demo_tools/custom_waiter.py
- agents_catalog/18-Wiley-online-library-agent/demo_tools/question.py
- agents_catalog/18-Wiley-online-library-agent/demo_tools/retries.py
- agents_catalog/18-Wiley-online-library-agent/generate_agent.py
- agents_catalog/18-Wiley-online-library-agent/requirements.txt
- agents_catalog/18-Wiley-online-library-agent/scenario_get_started_with_agents.py
- agents_catalog/18-Wiley-online-library-agent/scenario_resources/api_schema.yaml
- agents_catalog/18-Wiley-online-library-agent/scenario_resources/lambda_function.py
- agents_catalog/18-Wiley-online-library-agent/test/conftest.py
- agents_catalog/18-Wiley-online-library-agent/test/test_bedrock_agent_wrapper.py
- agents_catalog/18-Wiley-online-library-agent/wiley-search-agent-cfn.yaml
This PR adds requests to the Wiley API to search for health articles.
> Add Wiley search example

- README.md
- agents_catalog/README.md
- docs/src/content/docs/index.mdx
- multi_agent_collaboration/README.md
> Doc updates

- README.md
RedshiftPassword: Password for Redshift database login [Remember and store password securely] Need to add a note = > Only printable ASCII characters except for '/', '@', '"', ' ', '', ''' may be used.
> Update README.md for RedshiftPassword 

- ActionGroups/imaging-biomarker/preprocess-imaging-data.ipynb
emoved all output cells from the create_agent.ipynb notebook to eliminate embedded execution results that contained AWS account details and other potentially sensitive information. This helps maintain a cleaner repo and protects confidential data.
> removed output from ipynb files

- README.md
> Add template parameter guidance to README

- ActionGroups/imaging-biomarker/dummy_lambda.py
- ActionGroups/matplotbarchartlambda/matplotbarchartlambda.py
> backend updates to send images to presigned urls

- agent_build.yaml
- agents_catalog/18-Wiley-OA-life-sciences-agent/wiley-search-agent-cfn.yaml
> Agent permission fix

- Infra_cfn.yaml
- README.md
> Provide existing network resources

- .github/workflows/deploy.yml
Added GitHub Action script to package and deploy CloudFormation templates to public S3 buckets.
> Add GHA for Cfn Deployment

- agents_catalog/15-clinical-study-research-agent/clinical-study-agent.yaml
- multi_agent_collaboration/cancer_biomarker_discovery/SupervisorAgent/supervisor_agent.yaml
- multi_agent_collaboration/cancer_biomarker_discovery/agent_build.yaml
- multi_agent_collaboration/cancer_biomarker_discovery/agents/Statistician.yaml
#141 
Resolves matplotlib error in lambda layer
> Simple stats fix

- multi_agent_collaboration/cancer_biomarker_discovery/SupervisorAgent/supervisor_agent.yaml
Fix issue with AWSLambdaPowertoolsPythonV3 region preventing deployment outside of us-east-1
> Replace powertools layer region with pseudoparameter

- Infra_cfn.yaml
- agent_build.yaml
- build_agents.sh
- streamlitapp-agentcore/Dockerfile.txt
- streamlitapp-agentcore/app.py
- streamlitapp-agentcore/requirements.txt
- streamlitapp-agentcore/streamlit_build_agentcore.yaml
- streamlitapp/Infra_cfn.yaml
- streamlitapp/streamlit_build.yaml
We have added streamlitapp-agentcore folder to create a second streamlit ui for agentcore version.
> Strands streamlit UI addition

- agents_catalog/28-Research-agent-biomni-gateway-tools/agent/agent_config/agent.py
- Fix error handling: change 'raise f-string' to 'raise Exception(f-string)'
> Improve agent error handling

- agents_catalog/29-Clinical-PreVisit-Questionnaire/.gitignore
- agents_catalog/29-Clinical-PreVisit-Questionnaire/README.md
- agents_catalog/29-Clinical-PreVisit-Questionnaire/config/requirements.txt
- agents_catalog/29-Clinical-PreVisit-Questionnaire/demo_capabilities.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/fast_demo.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/full_questionnaire_demo.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/interactive_demo.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/main.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/run_demo.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/speed_comparison.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/__init__.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/__init__.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/pvq_agent.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/pvq_agent_fast.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/pvq_agent_ultra_fast.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/__init__.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/basic_info.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/health_maintenance.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/medical_history.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/medications.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/social_history.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/symptoms.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/agents/tools/utilities.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/models/__init__.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/models/patient_data.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/utils/__init__.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/utils/pdf_generator.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/src/utils/validators.py
- agents_catalog/29-Clinical-PreVisit-Questionnaire/tests/test_agent.py
This is a Strands Agent for filling up previsit questionnaire for patients. 
> Previsit Questionnaire
